### ISSUE TITLE
outpost config fields `kubernetes_ingress_secret_name` and `object_naming_template` are not written

### ISSUE THREAD

**Issue by tyriis** [goauthentik/terraform-provider-authentik#101]
### Description
The fields in `authentik_outpost.config` are not all recognised/applied.
Fields:
- kubernetes_ingress_secret_name
- object_naming_template

these 2 are always using the system default values.
Others seem to work fine (not tested all).
Changing these values in the authentik admin ui works as intended.

### Example:
```
terraform {
  required_providers {
    authentik = {
      source  = "goauthentik/authentik"
      version = "2022.1.1"
    }
  }
}

data "authentik_flow" "default_provider_authorization_explicit_consent" {
  slug = "default-provider-authorization-explicit-consent"
}

resource "authentik_provider_proxy" "test" {
  name               = "test"
  internal_host      = "http://test.default.svc.cluster.local"
  external_host      = "https://test.domain.io"
  authorization_flow = data.authentik_flow.default_provider_authorization_explicit_consent.id
}

resource "authentik_service_connection_kubernetes" "local" {
  name  = "Local Kubernetes Cluster"
  local = true
}

resource "authentik_outpost" "test" {
  name               = "test"
  service_connection = authentik_service_connection_kubernetes.local.id
  protocol_providers = [
    authentik_provider_proxy.test.id
  ]
  type = "proxy"
  config = jsonencode(
    {
      authentik_host                 = "https://authentik.domain.io"
      authentik_host_browser         = ""
      authentik_host_insecure        = false
      container_image                = null
      docker_labels                  = null
      docker_map_ports               = true
      docker_network                 = null
      kubernetes_disabled_components = []
      kubernetes_image_pull_secrets  = []
      kubernetes_ingress_annotations = {
        "cert-manager.io/cluster-issuer"                   = "letsencrypt-production"
        "traefik.ingress.kubernetes.io/router.entrypoints" = "websecure"
      }
      kubernetes_ingress_secret_name = "authentik-outpost-test-cert"
      kubernetes_namespace           = "authentik-system"
      kubernetes_replicas            = 1
      kubernetes_service_type        = "ClusterIP"
      log_level                      = "debug"
      object_naming_template         = "ak-outpost-%(name)s"
    }
  )
}

```
### Expected Behaviour
Config fields should accept all values.

### Workaround
Prevent creation of ingress and create ingress with terraform :/

**Comment by tyriis** [comment]
see: https://github.com/goauthentik/authentik/blob/42f5cf8c93ff5325c871a1a949cafb099edbc7eb/website/docs/outposts/index.md
for all config options

**Comment by patoarvizu** [comment]
I can confirm this is an issue for me as well.

I'm trying to run three outposts deployed on the same namespace, with different hostnames, but because the `authentik_outpost` resource gets created with the same `kubernetes_ingress_secret_name` for all three (even though I'm explicitly setting it), only one of them works properly.

**Comment by BeryJu** [comment]
Could you try with the latest version of the provider? I removed some code which merged the default settings with the user supplied ones, which is what I assumed caused this behaviour

**Comment by tyriis** [comment]
@BeryJu this is solved thanks for the fix.

**Comment by patoarvizu** [comment]
I can confirm this worked for me too, thanks! 👍
