### ISSUE TITLE
data authentik_flow always errors

### ISSUE THREAD

**Issue by jtcarnes** [goauthentik/terraform-provider-authentik#205]
The example given in for data authentik_flow always errors when used, ie

```hcl
data "authentik_flow" "default-authorization-flow" {
  slug = "default-provider-authorization-implicit-consent"
}
```

it returns:
```bash
│ Error: No matching flows found
│ 
│   with data.authentik_flow.default-authorization-flow,
│   on authentik.tf line 47, in data "authentik_flow" "default-authorization-flow":
│   47: data "authentik_flow" "default-authorization-flow" {
```

I can query the api by hand on my fresh instance and know its there. The openapi gui even finds it when submitting by hand. I can I can communicate with authentik fine as I can create the rest of the resources using tf.

Versions:
TF provider: 2022.6.3
Authentik instance: 2022.5.2

**Comment by BeryJu** [comment]
Hmmm, I'm not able to reproduce this, the datasource works both in the acceptance tests and my terraform setup. You can try setting `TF_LOG=trace` to see the HTTP request being sent

This exact snippet is used in tests https://github.com/goauthentik/terraform-provider-authentik/blob/main/internal/provider/data_source_flow_test.go, where the found flow's designation is checked

**Comment by jtcarnes** [comment]
I tried it again today and it worked fine. No change between yesterday and today. Very odd, but its resolved.
