### ISSUE TITLE
Include `sub_text` in `authentik_stage_prompt_field`

### ISSUE THREAD

**Issue by mittler-works** [goauthentik/terraform-provider-authentik#371]
Authentik allows to add a "Help text" to your prompt field.
If you export a flow containing a prompt field that contains a "Help Text", you can see this "Help Text" gets exported to the key `sub_text` and you can also see it in the model [here](https://github.com/goauthentik/authentik/blob/main/authentik/stages/prompt/models.py#L137) and its support through authentik api [here](https://github.com/goauthentik/authentik/blob/main/authentik/stages/prompt/api.py#L63).

This field is an important one when it comes to static fields where you want to just display some text, as this `sub_text` is the value which gets displayed.

So it would be nice, if this value could be set through the terraform provider as well.

**Comment by BeryJu** [comment]
Thanks for letting us know about this, we don't have an automated way to match the API schema to the terraform provider to notify us when fields might be missing here

**Comment by mittler-works** [comment]
**Wow that was fast** - thanks a lot! I've found some more missing keys and will create another issue for them.

Soon we will have automated our entire authentication deployment :raised_hands: Thank you for this Terraform Provider!
