### ISSUE TITLE
How to customize?

### ISSUE THREAD

**Issue by alexppg** [goauthentik/terraform-provider-authentik#393]
Hello there! 
Is there a way to customize authentik via terraform? Like it's done in this documentation page: https://goauthentik.io/docs/interfaces/user/customization

I've manually edited the tenant's "Other global settings", but there's no way to use that setting in the authentik_provider resource, as far as I've seen.

Thanks!

**Comment by BeryJu** [comment]
You can make these changes with the tenant resource https://registry.terraform.io/providers/goauthentik/authentik/latest/docs/resources/tenant

**Comment by alexppg** [comment]
I was coming to say that, I don't know how I didn't saw it in the documentation. Sorry and thanks!
