### ISSUE TITLE
Cannot manage Outpost integrations

### ISSUE THREAD

**Issue by vincent-lg18** [goauthentik/terraform-provider-authentik#514]
## Problem

It would be great to manage Outpost integrations from your Terraform provider.

In our `authentik_outpost`, we have to set the `service_connection` parameter to the ID of an Outpost integrations. But there isn't any data or resources that can be used to reference an outpost integration.

## Solution

Something like this to create outpost would be great: 

```hcl
resource "authentik_outpost_integration" "docker-integration" { 
  type  = "docker" # docker or k8s
  local = true
  name  = "docker-local"
  url   = "unix://..." 
}
```

**Comment by rissson** [comment]
There is https://registry.terraform.io/providers/goauthentik/authentik/latest/docs/resources/service_connection_docker and https://registry.terraform.io/providers/goauthentik/authentik/latest/docs/resources/service_connection_kubernetes to do so.

**Comment by vincent-lg18** [comment]
Okay thank you, maybe it should be in System instead of Applications in the documentation? Because the Outpust Integration menu is in System in Authentik dashboard
