### ISSUE TITLE
Unable to enable applications on an Outpost using terraform

### ISSUE THREAD

**Issue by emouawad** [goauthentik/terraform-provider-authentik#556]
Neither authentik_application nor authentik_outpost allow enabling applications on an Outpost.

Applications need to be selected on the outpost for the Proxy Provider to work and add the Ingress Endpoint for reverse-proxy auth to work.

**Comment by rissson** [comment]
`authentik_outpost` allows for selecting providers, as providers (not applications) are attached to outposts. Check out the `protocol_providers` option at https://registry.terraform.io/providers/goauthentik/authentik/latest/docs/resources/outpost

**Comment by emouawad** [comment]
![image](https://github.com/user-attachments/assets/c1c8b920-b75a-403f-b045-3ef69ede0d9d)
![image](https://github.com/user-attachments/assets/c167c9a2-3866-4a88-aa55-c27e097e3bdf)

@rissson I don't think i was clear enough in describing the issue.

As it looks from the screenshot, using the UI: Applications have to be selected for the ingress Rule to be enabled in kubernetes Ingress, if the app is not selected on the provider, the routing is not enabled.
