### ISSUE TITLE
Create API access token through terraform?

### ISSUE THREAD

**Issue by panos-indev** [goauthentik/terraform-provider-authentik#90]
I am setting up authentik with manually deployed LDAP outpost and I figured out how to create almost everything, including the bind dn account as a service account, through terraform. The thing I can't do is create an API access token to use with the bind dn account. This would require a new resource (authentik_api_token) unless there is a magic user attribute which makes authentik create an API token on user creation.

**Comment by BeryJu** [comment]
D'oh I completely missed that resource, I thought I pretty much had all of them covered.
